// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7rrI2c89RLYyj1ZdiQUpw6NM_s9PhIns',
    appId: '1:1099449673763:web:9a8291cb0b0f717031e996',
    messagingSenderId: '1099449673763',
    projectId: 'internship-management-pl-5ad66',
    authDomain: 'internship-management-pl-5ad66.firebaseapp.com',
    storageBucket: 'internship-management-pl-5ad66.firebasestorage.app',
    measurementId: 'G-E9CET21PKG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDT8XB6eAUMz9ZO8m900yH0CcyfV0Z4SSw',
    appId: '1:1099449673763:android:599544616fbfb79d31e996',
    messagingSenderId: '1099449673763',
    projectId: 'internship-management-pl-5ad66',
    storageBucket: 'internship-management-pl-5ad66.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7rrI2c89RLYyj1ZdiQUpw6NM_s9PhIns',
    appId: '1:1099449673763:web:f482246d5515278631e996',
    messagingSenderId: '1099449673763',
    projectId: 'internship-management-pl-5ad66',
    authDomain: 'internship-management-pl-5ad66.firebaseapp.com',
    storageBucket: 'internship-management-pl-5ad66.firebasestorage.app',
    measurementId: 'G-F4CYGETDE6',
  );
}
